### ISSUE TITLE
Fase 2.1: Agrupar columnas/Funciones

### ISSUE THREAD

**Issue by Iara-AC** [Iara-AC/project-da-promo-K-modulo-3-team-1#11]
Agrupar las columnas que tienen  el mismo tipo de 'problema'. Y así podemos crear funciones para poder solucionar problemas de una vez varias columnas con una única función. 

- [x] Identificar que columnas tienen el mismo problema y que problemas es.
- [x] Crear una función para transformar la información.
- [x] Comprobar que todas las funciones funcionen xD

**Comment by kaleeshy6162** [comment]
## FUNCIONES :

- [x]  Función de string a int; columna age / col. monthly_income /col. monthly_rate / col. yearsincurrentrole / col. salary / col. hourlyrate y dailyrate (relación entre las dos)

- [x] Función ejecute un ROUND;
col. daily_rate / col. performancerate

- [x]  Función conversión nº absoluto;
col. distanceformhome

- [x] Función de float a string;
col. educationfield

- [x]  Función que quede con el 1 digito de un numero de dos digitos; 
col. enviromentsatisfaction

- [x]  Función cambio tipográfico (de un tipo de string a otro tipo de string);
col. gender / col. matrialstatus / col.roledepartament

- [x]  Función combiar coma por punto;
col. totalworkingyears / col. workinglifebalance / col. yearsincuurrentrole / col. sameasmonthlyincome / col. salary

- [x]  Función que iguale, 1-Yes, 0-No;   (True/False NO  por que es booleano)
col. remotework
