### ISSUE TITLE
Fase 1: Análisis Exploratorio de Datos(EDA).

### ISSUE THREAD

**Issue by kaleeshy6162** [Iara-AC/project-da-promo-K-modulo-3-team-1#4]

**Comment by kaleeshy6162** [comment]
- [x] Analizar columnas para corroborar la info.
- [x] Decidir la estrategia de limpieza.
- [x] Seleccionar las sustituciones.

**Comment by Iara-AC** [comment]
Hemos analizado las columnas con el metodo Unique()
